"""Initial_schema_setup

Revision ID: 29d4644d3908
Revises:
Create Date: 2025-08-01 17:55:15.982014

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '29d4644d3908'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'codes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_codes_id'), 'codes', ['id'], unique=False)
    op.create_index(op.f('ix_codes_name'), 'codes', ['name'], unique=False)
    op.create_table(
        'code_versions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code_id', sa.Integer(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['code_id'],
            ['codes.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_code_versions_id'), 'code_versions', ['id'], unique=False
    )
    op.create_table(
        'parsing_results',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code_version_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['code_version_id'],
            ['code_versions.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_parsing_results_id'), 'parsing_results', ['id'], unique=False
    )
    op.create_table(
        'parsing_result_versions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('parsing_result_id', sa.Integer(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['parsing_result_id'],
            ['parsing_results.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_parsing_result_versions_id'),
        'parsing_result_versions',
        ['id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_parsing_result_versions_id'),
        table_name='parsing_result_versions',
    )
    op.drop_table('parsing_result_versions')
    op.drop_index(op.f('ix_parsing_results_id'), table_name='parsing_results')
    op.drop_table('parsing_results')
    op.drop_index(op.f('ix_code_versions_id'), table_name='code_versions')
    op.drop_table('code_versions')
    op.drop_index(op.f('ix_codes_name'), table_name='codes')
    op.drop_index(op.f('ix_codes_id'), table_name='codes')
    op.drop_table('codes')
    # ### end Alembic commands ###
